// HCG LAUNCH-GATE REGISTRY — single source of truth for the control matrix
// (areas A–I) and the 30 adversarial scenarios. docs/launch-gate/*.md
// render from / reference this file; tests/launch-gate-framework.test.mjs
// validates it (no PROVEN without strong evidence, every scenario fully
// specified, every probe/contract reference resolvable).
//
// Baseline: origin/main eb43368 (assessed 2026-10-03). Status is the state
// of MAIN — an unmerged branch that fixes something is recorded in
// `branchFix`, and does not change the status until it is integrated and
// the evidence is re-run on the integrated tree.
//
// Workstream owners:
//   WS-FIN  Financial Fortress            WS-FRAUD  Telephony Fraud Fortress
//   WS-BILL Customer Allowance/Billing    WS-ID     Customer Identity/Carrier Abstraction
//   WS-CARR Carrier/Routing research      WS-GATE   Launch gate (this branch)
//   WS-SEC  existing security branches (security/voice-surface-p0, security/supabase-staging-remediation, fix/process-endpoint-webhook-auth)
//   WS-DEL  existing call-delivery branches (p0/call-delivery-resilience, readiness/*)
//   OPS     Andrew / provider consoles (Twilio, Stripe, RevenueCat, App Store, Railway, Supabase)

const ci = ref => ({ kind: 'code-inspection', ref });
const doc = ref => ({ kind: 'design-doc', ref });
const test = ref => ({ kind: 'automated-test', ref });

export const BASELINE = { ref: 'origin/main', sha: 'eb43368', assessed: '2026-10-03' };

export const CONTROLS = [
  // ------------------------------------------------------------ A SECURITY
  { id: 'A1', area: 'A', title: 'Twilio webhook authenticity (HTTP routes + /media-stream WebSocket)', status: 'FAIL', blocker: true, owner: 'WS-SEC',
    evidence: [ci('server.js:641-688 /voice signature gates only activation stamp'), ci('server.js:843,970,996,1047 no check'), ci('services/liveMonitoring/mediaStreamServer.js:29-49 shadow only')],
    probes: ['PR-01', 'PR-02'], branchFix: 'security/voice-surface-p0 7f0bae3 (enforced guard + per-call stream token; staging-verified); fix/process-endpoint-webhook-auth e2895f1 (/process only — superseded by voice-p0)' },
  { id: 'A2', area: 'A', title: 'Replay protection (Twilio, RevenueCat)', status: 'FAIL', blocker: true, owner: 'WS-SEC / WS-BILL',
    evidence: [ci('routes/mobileApi.js:1212-1300 RevenueCat: no event-id dedupe, no timestamp'), ci('no Twilio CallSid dedupe found')],
    branchFix: 'none found for RevenueCat replay; voice-p0 stream token is one-time (covers /media-stream only)' },
  { id: 'A3', area: 'A', title: 'Stripe webhook signature + event-id dedupe', status: 'PARTIAL', blocker: false, owner: 'WS-BILL',
    evidence: [ci('routes/billing.js:551-567 constructEvent on raw body'), ci('routes/billing.js:594 claimWebhookEvent (migration 014)')],
    note: 'Implemented; no automated test exercises signature rejection or duplicate delivery.' },
  { id: 'A4', area: 'A', title: 'RevenueCat webhook authentication', status: 'PARTIAL', blocker: false, owner: 'WS-BILL',
    evidence: [ci('routes/mobileApi.js:1213-1223 static shared header, non-constant-time compare, fails closed when unset')] },
  { id: 'A5', area: 'A', title: 'Account (household) isolation', status: 'PARTIAL', blocker: false, owner: 'WS-SEC',
    evidence: [ci('middleware/requireAuthApi.js derives household from auth user'), ci('server.js:1539,1552; mobileApi.js:1110,1123 scoped by req.household.id')],
    note: 'No cross-household negative test suite; required before PROVEN (scenario-independent manual/automated test M-A5).' },
  { id: 'A6', area: 'A', title: 'Admin isolation', status: 'PARTIAL', blocker: false, owner: 'WS-SEC',
    evidence: [ci('middleware/requireAdmin.js:7-10 role from user_roles'), test('tests/admin-business-auth.test.mjs')],
    note: 'Admin actions log is in-memory only (see I1).' },
  { id: 'A7', area: 'A', title: 'Secrets: none committed; provider credentials least-privilege', status: 'PARTIAL', blocker: true, owner: 'OPS / WS-SEC',
    evidence: [ci('tree scan 2026-10-03: no live keys; fixtures only'), doc('memory: master Twilio auth token used by backend (catastrophic risk review 2026-10-01)')],
    note: 'Repo is clean; but the backend holds the master Twilio account token, so a backend compromise = full account control (scenario S20). API key + subaccount separation not done.' },
  { id: 'A8', area: 'A', title: 'Rate limiting on unauthenticated endpoints', status: 'FAIL', blocker: true, owner: 'WS-FRAUD',
    evidence: [ci('no limiter on /register, /api/v1/register, /login, /forgot-password, /resend-confirmation, /api/v1/waiting-list')], probes: ['PR-11'],
    branchFix: 'readiness/android-call-delivery: per-household limits on authenticated voice routes only' },
  { id: 'A9', area: 'A', title: 'Supabase RLS / Data API grants', status: 'PARTIAL', blocker: true, owner: 'WS-SEC',
    evidence: [doc('security/supabase-staging-remediation: 057–061 applied+verified on STAGING only; prod runbook awaiting approval')] },
  { id: 'A10', area: 'A', title: 'Voice SDK client-origin calls cannot enter /voice', status: 'FAIL', blocker: true, owner: 'WS-SEC',
    evidence: [ci('server.js /voice: no From=client: reject on main')], branchFix: 'security/voice-surface-p0; readiness/ios-parity server.js:763' },
  { id: 'A11', area: 'A', title: 'No unauthenticated debug/telemetry write endpoints', status: 'PARTIAL', blocker: false, owner: 'WS-SEC',
    evidence: [ci('routes/mobileApi.js:1338 /debug/purchase-beacon (log-only, capped)')] },

  // ----------------------------------------------------------- B FINANCIAL
  { id: 'B1', area: 'B', title: 'Hard PSTN call-duration bound (ends the billable leg, not just monitoring)', status: 'FAIL', blocker: true, owner: 'WS-FIN',
    evidence: [ci('server.js:287 <Dial> has no timeLimit'), ci('mediaStreamHandler.js:360-393 30-min cap closes stream only')], probes: ['PR-06'],
    branchFix: 'feature/financial-safety-hard-limits 30d454c: timeLimit (SAFETY_MAX_CALL_MINUTES=240) — wired, migration 056 not applied' },
  { id: 'B2', area: 'B', title: 'Per-customer allowance enforced (hard containment)', status: 'FAIL', blocker: true, owner: 'WS-FIN / WS-BILL',
    evidence: [ci('services/businessMetrics/fairUse.js:15 reporting only')], contract: ['FC-1', 'FC-4', 'FC-5'],
    branchFix: '30d454c: 056 household_usage_periods + monitoringGate (stops monitoring; never refuses the call)' },
  { id: 'B3', area: 'B', title: 'Per-household concurrent-call cap', status: 'FAIL', blocker: true, owner: 'WS-FIN',
    evidence: [ci('only global 200-stream cap, services/liveMonitoring/monitoringLimit.js:62; nothing per household')], contract: ['FC-2'],
    branchFix: '30d454c SAFETY_MAX_CALLS_PER_HOUSEHOLD=3; voice-p0 2 streams/household' },
  { id: 'B4', area: 'B', title: 'Global spend ceiling that refuses new cost', status: 'FAIL', blocker: true, owner: 'WS-FIN',
    evidence: [ci('absent on main')], contract: ['FC-7'], probes: ['PR-12'],
    branchFix: '30d454c admit_call daily/hourly £ caps (056); provider-neutral-billing-ledger spendGuard is recommend-only, not wired' },
  { id: 'B5', area: 'B', title: 'Rate-of-spend breaker', status: 'FAIL', blocker: true, owner: 'WS-FIN',
    evidence: [ci('server.js:768-797 rapid-abuse detection alerts only, never blocks')], contract: ['FC-8'],
    branchFix: '30d454c burst 10/120s, 6/caller/600s' },
  { id: 'B6', area: 'B', title: 'Admission fails CLOSED when DB / authorisation service unavailable', status: 'FAIL', blocker: true, owner: 'WS-FIN',
    evidence: [ci('main has no admission step; every call dialled')], contract: ['FC-6'],
    branchFix: '30d454c callAdmission.js:144-153 falls back to in-memory limits and does NOT evaluate £ ceilings when DB times out (partial fail-open); unsigned /voice admitted and not counted (:124-126)' },
  { id: 'B7', area: 'B', title: 'Atomic authorisation across server instances', status: 'FAIL', blocker: true, owner: 'WS-FIN',
    evidence: [ci('all counters in-process memory')], contract: ['FC-2'],
    branchFix: '056 pg_advisory_xact_lock + SELECT FOR UPDATE (requires 056 applied; contract must be bound to pglite/staging Postgres)' },
  { id: 'B8', area: 'B', title: 'Ledger idempotency', status: 'FAIL', blocker: true, owner: 'WS-FIN',
    evidence: [ci('no ledger on main')], contract: ['FC-3'],
    branchFix: '051 unique (source_system, entry_key) — staging only, writer/reconciler unscheduled' },
  { id: 'B9', area: 'B', title: 'Malformed / overflow cost input rejected', status: 'UNPROVEN', blocker: true, owner: 'WS-FIN',
    evidence: [ci('n/a on main')], contract: ['FC-4'], branchFix: 'ledger services/ledger/contract.js:37,60-108 rejects negative/non-finite; no upper bound found' },
  { id: 'B10', area: 'B', title: 'Provider cost mismatch detected and acted on (reconciliation)', status: 'UNPROVEN', blocker: true, owner: 'WS-FIN',
    evidence: [doc('billing ledger branch: estimate-vs-ledger check, not scheduled')] },
  { id: 'B11', area: 'B', title: 'Unentitled / exhausted household cannot generate HCG cost', status: 'FAIL', blocker: true, owner: 'WS-FIN / WS-BILL',
    evidence: [ci('server.js:797-829 entitlement gates monitoring only; inbound leg still connected')] },

  // ------------------------------------------------------ C TELEPHONY FRAUD
  { id: 'C1', area: 'C', title: 'Premium/high-cost destinations can never be dialled or messaged', status: 'PARTIAL', blocker: true, owner: 'WS-FRAUD',
    evidence: [test('tests/launch-gate probes PR-05 (no outbound PSTN leg on main)'), ci('phone.js:17-36 accepts 09x/087x/070 as household destination')], probes: ['PR-04', 'PR-05'],
    note: 'Safe today only because no PSTN leg exists. SMS (C9) does reach customer-controlled numbers. Validation absent.' },
  { id: 'C2', area: 'C', title: 'International destinations blocked (code + Twilio geo-permissions)', status: 'PARTIAL', blocker: true, owner: 'WS-FRAUD / OPS',
    evidence: [doc('memory: outbound voice geo all OFF 2026-09-30; SMS geo pending in Console — no exported config in repo')], probes: ['PR-05'] },
  { id: 'C3', area: 'C', title: 'Trusted-contact bypass resistant to caller-ID spoofing / collisions', status: 'FAIL', blocker: true, owner: 'WS-FRAUD',
    evidence: [ci('server.js:690-716 From last-10-digit match skips all screening')], probes: ['PR-03'] },
  { id: 'C4', area: 'C', title: 'Forwarding loop cannot generate cost', status: 'PARTIAL', blocker: true, owner: 'WS-FRAUD / WS-CARR',
    evidence: [test('PR-05: no PSTN leg'), ci('phone.js:48 wouldCreateForwardingLoop (own number only)')] },
  { id: 'C5', area: 'C', title: 'Multi-number loop cannot generate cost', status: 'PARTIAL', blocker: true, owner: 'WS-FRAUD / WS-CARR',
    evidence: [test('PR-05: no PSTN leg')], note: 'Becomes FAIL the moment any branch adds a PSTN fallback / trusted-bypass dial.' },
  { id: 'C6', area: 'C', title: 'Repeated-calling / traffic pumping bounded', status: 'FAIL', blocker: true, owner: 'WS-FRAUD',
    evidence: [ci('no per-caller or per-household call-rate limit on main')], contract: ['FC-8'] },
  { id: 'C7', area: 'C', title: 'Provisioning fraud: no orphaned/unauthorised number purchases', status: 'FAIL', blocker: true, owner: 'WS-FRAUD / WS-ID',
    evidence: [ci('twilioProvisioning.js:125-160 no release on assign error')], probes: ['PR-07'],
    branchFix: 'fix/nonprod-telephony-mutation-guard b337438 (environment side only)' },
  { id: 'C8', area: 'C', title: 'Multi-account abuse by one actor', status: 'FAIL', blocker: true, owner: 'WS-FRAUD',
    evidence: [ci('no per-person/device/payment-instrument limit found')], probes: ['PR-11'] },
  { id: 'C9', area: 'C', title: 'SMS can only be sent to the verified household number, capped', status: 'FAIL', blocker: true, owner: 'WS-SEC',
    evidence: [ci('mediaStreamHandler.js:277-294 SMS to/from from client stream params')], probes: ['PR-02'],
    branchFix: 'security/voice-surface-p0: numbers from server-side registry; 3 SMS/household/day, 30/hour' },
  { id: 'C10', area: 'C', title: 'Provider-level guardrails (geo permissions, usage triggers that suspend, low balance/auto-recharge off)', status: 'UNPROVEN', blocker: true, owner: 'OPS',
    evidence: [doc('memory 2026-09-30: voice geo off; SMS geo + auto-recharge pending'), doc('docs/integration/2026-10-04-PROVIDER_FINANCIAL_CONTAINMENT_FINAL.md §2 (official-docs classification, 2026-10-04)')],
    note: 'Needs a dated console export (provider-config-export). Twilio documents NO account spend limit; usage triggers are alert-only; voice geo is API-changeable (SMS geo is not); balance stop leaks (in-progress calls, undocumented negative). Checklist: docs/integration/2026-10-04-TWILIO_CONTAINMENT_CHECKLIST.md (not executed).' },

  // -------------------------------------------------------------- D BILLING
  { id: 'D1', area: 'D', title: '£5.99 entitlement (price as approved, consistent across channels)', status: 'UNPROVEN', blocker: true, owner: 'WS-BILL / OPS',
    evidence: [ci('candidate: app + checkout + membership label read the price from StoreKit / the Stripe Price (no literal); website/terms/guides £5.99 in source (2026-10-05)'), doc('£5.99 APPROVED 2026-10-04; live Stripe Price + App Store IAP still £4.99 — cutover: docs/launch/2026-10-05-PRICE-CUTOVER-CHECKLIST.md')] },
  { id: 'D2', area: 'D', title: 'Stripe lifecycle (create/renew/cancel/delete)', status: 'PARTIAL', blocker: false, owner: 'WS-BILL',
    evidence: [ci('routes/billing.js:572-618'), test('tests/cancellation-deactivation-safety.test.mjs')] },
  { id: 'D3', area: 'D', title: 'Apple IAP entitlement (incl. delay)', status: 'UNPROVEN', blocker: true, owner: 'WS-BILL', evidence: [ci('via RevenueCat only')] },
  { id: 'D4', area: 'D', title: 'RevenueCat events (TRANSFER/EXPIRATION/BILLING_ISSUE/ordering)', status: 'PARTIAL', blocker: true, owner: 'WS-BILL',
    evidence: [test('tests/revenuecat-webhook.test.mjs'), ci('BILLING_ISSUE/CANCELLATION no-op; no ordering guard (019 is Stripe only)')] },
  { id: 'D5', area: 'D', title: 'Renewal', status: 'UNPROVEN', blocker: false, owner: 'WS-BILL', evidence: [] },
  { id: 'D6', area: 'D', title: 'Cancellation keeps service to period end, then stops cost', status: 'PARTIAL', blocker: false, owner: 'WS-BILL',
    evidence: [ci('billing.js:618 cancel_at_period_end'), test('tests/cancellation-deactivation-safety.test.mjs')] },
  { id: 'D7', area: 'D', title: 'Sandbox/production separation', status: 'FAIL', blocker: true, owner: 'WS-BILL',
    evidence: [ci('mobileApi.js:1290-1298 environment ignored')], probes: ['PR-08'],
    branchFix: 'fix/revenuecat-sandbox-environment-guard f5a920e — skips provisioning but STILL grants entitlement (partial)' },
  { id: 'D8', area: 'D', title: 'Payment issue / grace bounded', status: 'PARTIAL', blocker: false, owner: 'WS-BILL',
    evidence: [ci('past_due counts as entitled (013:217, 015:76, 019:140); number grace 30 days')] },
  { id: 'D9', area: 'D', title: 'Top-up', status: 'UNPROVEN', blocker: false, owner: 'WS-BILL', evidence: [ci('absent; 056 adds bonus_monitored_seconds column only')] },
  { id: 'D10', area: 'D', title: 'Duplicate billing webhook is a no-op', status: 'PARTIAL', blocker: true, owner: 'WS-BILL',
    evidence: [ci('Stripe dedupe present; RevenueCat none')], contract: ['FC-3'] },
  { id: 'D11', area: 'D', title: 'Expiry during an active call bounds cost', status: 'FAIL', blocker: true, owner: 'WS-FIN / WS-BILL',
    evidence: [ci('no mid-call entitlement recheck on any branch')] },

  // ------------------------------------------------------------- E IDENTITY
  { id: 'E1', area: 'E', title: 'Permanent HCG account number (customer-facing, carrier-independent)', status: 'FAIL', blocker: false, owner: 'WS-ID',
    evidence: [ci('households.id uuid only; no account number')] },
  { id: 'E2', area: 'E', title: 'Routing-number independence (identity survives number change)', status: 'FAIL', blocker: false, owner: 'WS-ID',
    evidence: [ci('households.twilio_number mutable column; resubscribe buys a new number twilioProvisioning.js:354-359')], probes: ['PR-09'] },
  { id: 'E3', area: 'E', title: 'Carrier migration without customer re-setup', status: 'UNPROVEN', blocker: false, owner: 'WS-ID / WS-CARR', evidence: [] },
  { id: 'E4', area: 'E', title: 'Historical number mapping', status: 'FAIL', blocker: false, owner: 'WS-ID', evidence: [ci('no household_numbers history; quarantine table partial')] },
  { id: 'E5', area: 'E', title: 'Subscription preserved across number/carrier change', status: 'UNPROVEN', blocker: false, owner: 'WS-ID / WS-BILL', evidence: [] },

  // -------------------------------------------------------- F CALL DELIVERY
  { id: 'F1', area: 'F', title: 'Locked-screen ringing (Android FSI / iOS CallKit)', status: 'UNPROVEN', blocker: true, owner: 'WS-DEL', evidence: [doc('Build 19 internal testing; FSI behaviour not accepted')] },
  { id: 'F2', area: 'F', title: 'Push failure ⇒ caller told, no cost-bearing fallback', status: 'PARTIAL', blocker: false, owner: 'WS-DEL',
    evidence: [ci('server.js:996-1030 apology + hangup + alert')] },
  { id: 'F3', area: 'F', title: 'App unregistered ⇒ no dial, apology', status: 'PARTIAL', blocker: false, owner: 'WS-DEL', evidence: [ci('server.js:294-316')] },
  { id: 'F4', area: 'F', title: 'App offline', status: 'PARTIAL', blocker: false, owner: 'WS-DEL', evidence: [ci('20s Client timeout then apology')] },
  { id: 'F5', area: 'F', title: 'No answer / busy / decline', status: 'PARTIAL', blocker: false, owner: 'WS-DEL', evidence: [ci('/call-delivery-failed')] },
  { id: 'F6', area: 'F', title: 'Permissions revoked (mic, notifications, FSI)', status: 'UNPROVEN', blocker: true, owner: 'WS-DEL', evidence: [] },
  { id: 'F7', area: 'F', title: 'Android / iPhone parity', status: 'UNPROVEN', blocker: true, owner: 'WS-DEL', evidence: [doc('readiness/ios-parity eab9caa, not device-verified')] },

  // -------------------------------------------------- G BUSINESS CONTINUITY
  { id: 'G1', area: 'G', title: 'Database outage: no uncontrolled cost, defined caller experience', status: 'PARTIAL', blocker: true, owner: 'WS-FIN / WS-DEL',
    evidence: [ci('households.js:29-32 lookup error ⇒ null ⇒ apology for ALL calls incl. trusted (cost-safe, service-unsafe)')], probes: ['PR-09'] },
  { id: 'G2', area: 'G', title: 'AI outage: call continues, no runaway retries', status: 'PARTIAL', blocker: false, owner: 'WS-FIN', evidence: [ci('transcribeChunk.js:44-46 returns null')] },
  { id: 'G3', area: 'G', title: 'Carrier (Twilio) outage', status: 'UNPROVEN', blocker: false, owner: 'WS-CARR', evidence: [] },
  { id: 'G4', area: 'G', title: 'HCG backend outage while forwarding remains active', status: 'UNPROVEN', blocker: true, owner: 'WS-CARR / OPS',
    evidence: [doc('Twilio retries /voice; fallback URL config not in repo')] },
  { id: 'G5', area: 'G', title: 'Compromised provider credentials: blast radius bounded', status: 'FAIL', blocker: true, owner: 'OPS / WS-SEC',
    evidence: [doc('backend uses master Twilio auth token (catastrophic risk review 2026-10-01)')] },
  { id: 'G6', area: 'G', title: 'Abnormal spend ⇒ automatic safe shutdown (not just alert)', status: 'FAIL', blocker: true, owner: 'WS-FIN', evidence: [ci('no kill switch on main')], probes: ['PR-12'] },
  { id: 'G7', area: 'G', title: 'Recovery runbook tested', status: 'UNPROVEN', blocker: true, owner: 'OPS', evidence: [] },

  // ------------------------------------------------ H CUSTOMER EXPERIENCE
  { id: 'H1', area: 'H', title: 'Onboarding', status: 'PARTIAL', blocker: false, owner: 'WS-DEL', evidence: [test('tests/customer-protection-steps.test.mjs')] },
  { id: 'H2', area: 'H', title: 'Forwarding setup and safe removal', status: 'PARTIAL', blocker: false, owner: 'WS-CARR', evidence: [test('tests/activation-instructions.test.mjs')] },
  { id: 'H3', area: 'H', title: 'Trusted contacts management', status: 'PARTIAL', blocker: false, owner: 'WS-FRAUD', evidence: [test('tests/contacts-sync.test.mjs')] },
  { id: 'H4', area: 'H', title: 'Usage display matches enforced meter', status: 'UNPROVEN', blocker: true, owner: 'WS-BILL', evidence: [] },
  { id: 'H5', area: 'H', title: 'Warning before allowance exhaustion', status: 'UNPROVEN', blocker: true, owner: 'WS-BILL', evidence: [] },
  { id: 'H6', area: 'H', title: 'Exhausted-allowance behaviour is explicit to customer and caller', status: 'UNPROVEN', blocker: true, owner: 'WS-BILL', evidence: [] },
  { id: 'H7', area: 'H', title: 'Cancellation tells customer to remove forwarding', status: 'PARTIAL', blocker: false, owner: 'WS-BILL', evidence: [ci('server.js:1313 /deactivation-instructions')] },
  { id: 'H8', area: 'H', title: 'Support can identify customer by account number', status: 'FAIL', blocker: false, owner: 'WS-ID', evidence: [ci('no account number (E1)')] },

  // ----------------------------------------------------------- I OPERATIONS
  { id: 'I1', area: 'I', title: 'Durable audit trail for admin and safety actions', status: 'FAIL', blocker: true, owner: 'WS-FIN',
    evidence: [ci('services/adminActionLog.js in-memory, 20 entries, lost on restart')], branchFix: '056 financial_safety_events' },
  { id: 'I2', area: 'I', title: 'Admin visibility of spend / usage', status: 'PARTIAL', blocker: false, owner: 'WS-FIN', evidence: [doc('memory: dashboard under-costing bugs; PR #51 draft')] },
  { id: 'I3', area: 'I', title: 'Alerting (and alerts are not the control)', status: 'PARTIAL', blocker: false, owner: 'WS-FIN', evidence: [test('tests/alerting.test.mjs')] },
  { id: 'I4', area: 'I', title: 'Emergency controls usable without a deploy', status: 'FAIL', blocker: true, owner: 'WS-FIN', evidence: [ci('none on main')], probes: ['PR-12'] },
  { id: 'I5', area: 'I', title: 'Provider-invoice reconciliation', status: 'UNPROVEN', blocker: true, owner: 'WS-FIN', evidence: [] },
  { id: 'I6', area: 'I', title: 'Migration control (unique numbers; history matches environments)', status: 'FAIL', blocker: true, owner: 'WS-GATE',
    evidence: [test('tests/launch-gate/migration-inventory.mjs: collisions 046, 055, 058, 060, 061 across branches')], probes: ['PR-10'] },
  { id: 'I7', area: 'I', title: 'Support diagnosis of a failed call', status: 'PARTIAL', blocker: false, owner: 'WS-DEL', evidence: [doc('incident triage script 8273215')] },
];

// Maximum-exposure figures quoted from
// feature/provider-neutral-billing-ledger:docs/finance/FINANCIAL_SAFETY_CONTROLS.md:53-58
// (modelled, not measured). "Unbounded" = no code bound exists on main.
const EXPO = 'feature/provider-neutral-billing-ledger:docs/finance/FINANCIAL_SAFETY_CONTROLS.md';

export const SCENARIOS = [
  { id: 'S1', title: 'One customer creates many accounts', owner: 'WS-FRAUD', mode: 'automated+manual', status: 'FAIL', controls: ['C8', 'A8'], probes: ['PR-11'],
    precondition: 'Attacker has N email addresses; registration open.', action: 'Script /api/v1/register + checkout/IAP for N accounts; each gets a Twilio number and monitoring.',
    expected: 'Per-person/device/payment-instrument and per-IP limits refuse account N+1; each account still individually capped (B2/B3).',
    maxExposure: 'Unbounded on main: N × (number rental + per-household flood, £225.32/day per 10-channel household per ' + EXPO + ')',
    evidence: 'Automated: rate-limit test on registration; manual: staging run of 20 sign-ups from one device/IP with result log.' },
  { id: 'S2', title: 'One actor provisions many numbers', owner: 'WS-FRAUD', mode: 'automated+manual', status: 'FAIL', controls: ['C7', 'C8', 'D7'], probes: ['PR-07', 'PR-08'],
    precondition: 'Sandbox IAP or complimentary invite or repeated provisioning failure.', action: 'Trigger provisioning repeatedly (sandbox grants; assign failures; invites).',
    expected: 'No number purchased without a production-verified paid entitlement; a global and per-actor purchase rate cap; failures release purchased numbers.',
    maxExposure: 'Unbounded number rental (≈£0.87/number/month observed, memory: 19 numbers £16.51/mo) + inbound cost on each.',
    evidence: 'PR-07 PASS + PR-08 PASS + manual staging sandbox purchase showing no Twilio purchase in console export.' },
  { id: 'S3', title: 'Premium destination added as trusted', owner: 'WS-FRAUD', mode: 'automated', status: 'PARTIAL', controls: ['C1'], probes: ['PR-04', 'PR-05'],
    precondition: 'Customer saves 09xx/087x/070 as trusted contact or household number.', action: 'Trigger any code path that might dial or message that number.',
    expected: 'Number rejected at input, and no code path ever dials/messages a customer-supplied number without an allow-list.',
    maxExposure: '£0 voice on main (no PSTN leg, PR-05); SMS to household number possible (C9).',
    evidence: 'PR-04 PASS + PR-05 PASS on the integrated tree; Twilio geo/premium export.' },
  { id: 'S4', title: 'International destination added as trusted', owner: 'WS-FRAUD', mode: 'automated+manual', status: 'PARTIAL', controls: ['C2'], probes: ['PR-05'],
    precondition: 'Trusted contact +882/+44 70/+1 etc.', action: 'As S3.', expected: 'As S3 + Twilio voice & SMS geo-permissions restricted to GB (exported).',
    maxExposure: '£0 voice on main; international SMS via forged /media-stream (S20/C9) is unbounded until voice-p0.',
    evidence: 'PR-05 PASS + provider-config-export of geo permissions (voice + SMS), dated.' },
  { id: 'S5', title: 'Caller spoofs a trusted number', owner: 'WS-FRAUD', mode: 'automated+manual', status: 'FAIL', controls: ['C3'], probes: ['PR-03'],
    precondition: 'Attacker knows a trusted contact\'s number (or any foreign number with the same last 10 digits).', action: 'Call the protected line presenting that CLI.',
    expected: 'Bypass decision uses exact E.164 match; STIR/SHAKEN attestation (where available) or other signal required; residual risk documented and accepted by Andrew.',
    maxExposure: 'Scam-protection failure (customer harm), not direct HCG £; cost = normal call cost.',
    evidence: 'PR-03 PASS; written risk acceptance for spoofed-CLI residual.' },
  { id: 'S6', title: '10 simultaneous calls with almost no allowance', owner: 'WS-FIN', mode: 'automated', status: 'FAIL', controls: ['B2', 'B3', 'B7'], contract: ['FC-2'],
    precondition: 'Household has 45 s remaining.', action: '10 concurrent /voice requests.',
    expected: 'Total reserved/granted ≤ remaining; per-household concurrent cap refuses the rest before any billable leg connects.',
    maxExposure: 'Main: 10 × unbounded duration (no timeLimit) ≈ £225.32/day per ' + EXPO,
    evidence: 'FC-2 PASS bound to the real implementation on pglite (two Node processes) + staging run with 10 real calls.' },
  { id: 'S7', title: 'Allowance reaches zero mid-call', owner: 'WS-FIN / WS-BILL', mode: 'automated+manual', status: 'FAIL', controls: ['B2', 'H6'], contract: ['FC-1'],
    precondition: 'Call in progress with 30 s remaining.', action: 'Keep talking for 10 min.',
    expected: 'Defined policy executed: billable cost after exhaustion bounded (monitoring ended AND PSTN leg bounded by timeLimit), customer + caller informed.',
    maxExposure: 'Main: no allowance; call bounded only by Twilio default limit.',
    evidence: 'Automated mid-call exhaustion test + staging call recording/Twilio call log showing end time.' },
  { id: 'S8', title: 'Monitoring terminates but PSTN leg remains billable', owner: 'WS-FIN', mode: 'automated+manual', status: 'FAIL', controls: ['B1'], probes: ['PR-06'],
    precondition: 'Call reaches 30-min monitoring cap.', action: 'Stay connected for hours.',
    expected: 'PSTN leg ended by a hard bound (Dial timeLimit / REST completion) independent of the WebSocket.',
    maxExposure: '£10.88/day per line for 24h trusted calls (' + EXPO + ')',
    evidence: 'PR-06 PASS + staging call that exceeds the configured limit with Twilio call record showing duration ≤ limit.' },
  { id: 'S9', title: 'Forwarding loop', owner: 'WS-FRAUD / WS-CARR', mode: 'automated+manual', status: 'PARTIAL', controls: ['C4'], probes: ['PR-05'],
    precondition: 'Customer forwards to HCG number; HCG delivery path dials the forwarded mobile.', action: 'Inbound call.',
    expected: 'No HCG leg ever dials a number that forwards back; loop detection (Diversion/ForwardedFrom/hop count) if a PSTN leg is ever added.',
    maxExposure: '£0 on main (no PSTN leg). Unbounded per call if a PSTN fallback is introduced.',
    evidence: 'PR-05 PASS on every integrated tree; manual: handset forwarding test on staging.' },
  { id: 'S10', title: 'Multi-number loop', owner: 'WS-FRAUD / WS-CARR', mode: 'automated+manual', status: 'PARTIAL', controls: ['C5'], probes: ['PR-05'],
    precondition: 'Two households forward to each other\'s HCG numbers / own numbers.', action: 'Inbound call.',
    expected: 'As S9.', maxExposure: 'As S9.', evidence: 'As S9.' },
  { id: 'S11', title: 'Duplicate webhook', owner: 'WS-BILL / WS-FIN', mode: 'automated', status: 'FAIL', controls: ['D10', 'B8', 'A2'], contract: ['FC-3'],
    precondition: 'Any billing or usage webhook.', action: 'Deliver the same event 5×, including concurrently.',
    expected: 'Applied exactly once.', maxExposure: 'RevenueCat: duplicate grant/provisioning attempts; ledger: double-count.',
    evidence: 'FC-3 PASS bound to real ledger + RevenueCat duplicate-delivery test.' },
  { id: 'S12', title: 'Replay', owner: 'WS-SEC', mode: 'automated', status: 'FAIL', controls: ['A1', 'A2'], probes: ['PR-01', 'PR-02'], contract: ['FC-3'],
    precondition: 'Captured genuine webhook/stream start.', action: 'Replay hours later.',
    expected: 'Rejected (signature + timestamp/nonce or one-time token).', maxExposure: 'Main: forged requests need no replay — unsigned accepted.',
    evidence: 'PR-01/PR-02 PASS + replay test of a stream token after use.' },
  { id: 'S13', title: 'Provider API timeout followed by retry', owner: 'WS-FRAUD / WS-FIN', mode: 'automated', status: 'UNPROVEN', controls: ['C7', 'B8'],
    precondition: 'Twilio REST call times out after the side effect happened.', action: 'Our code retries.',
    expected: 'Idempotent: retry detects the earlier side effect (lookup by FriendlyName/idempotency key) — no second purchase/charge.',
    maxExposure: 'Main: up to 5 purchases per household (DEFAULT_MAX_ATTEMPTS).', evidence: 'Automated fake-client test with timeout-after-success.' },
  { id: 'S14', title: 'Number purchase succeeds but HCG times out', owner: 'WS-FRAUD / WS-ID', mode: 'automated', status: 'FAIL', controls: ['C7'], probes: ['PR-07'],
    precondition: 'incomingPhoneNumbers.create succeeds; assign throws.', action: 'Provisioning run.',
    expected: 'Number released or reconciled to the household; no orphan.', maxExposure: '5 orphaned numbers per household per incident, indefinitely.',
    evidence: 'PR-07 PASS + reconciliation job listing Twilio numbers with no household.' },
  { id: 'S15', title: 'AI API becomes unavailable', owner: 'WS-FIN', mode: 'automated+manual', status: 'PARTIAL', controls: ['G2'],
    precondition: 'OpenAI returns 5xx/timeouts.', action: 'Calls continue.',
    expected: 'Calls delivered; no retry storm; cost bound unchanged; customer told monitoring unavailable.',
    maxExposure: 'Bounded by existing per-chunk calls; no retry loop found.', evidence: 'Automated: transcribe failure injection test; manual: staging with invalid key.' },
  { id: 'S16', title: 'Database becomes unavailable', owner: 'WS-FIN / WS-DEL', mode: 'automated+manual', status: 'PARTIAL', controls: ['G1', 'B6'], contract: ['FC-6'], probes: ['PR-09'],
    precondition: 'Supabase unreachable.', action: 'Inbound calls arrive.',
    expected: 'Fail closed on cost (no admission without authorisation) with explicit caller message; no in-memory fallback that skips £ ceilings.',
    maxExposure: 'Main: cost-safe (all calls rejected). 30d454c: in-memory fallback skips £ ceilings.',
    evidence: 'FC-6 PASS bound to real admission + staging DB-outage drill.' },
  { id: 'S17', title: 'Financial authorisation service unavailable', owner: 'WS-FIN', mode: 'automated', status: 'UNPROVEN', controls: ['B6'], contract: ['FC-6'],
    precondition: 'Admission RPC times out.', action: 'Inbound calls.', expected: 'Fail closed.', maxExposure: 'As S16.', evidence: 'FC-6 PASS bound to real admission.' },
  { id: 'S18', title: 'Global spend ceiling reached', owner: 'WS-FIN', mode: 'automated+manual', status: 'FAIL', controls: ['B4'], contract: ['FC-7'], probes: ['PR-12'],
    precondition: 'Company spend ≥ ceiling.', action: 'New calls.', expected: 'New cost refused; existing calls bounded; Andrew notified.',
    maxExposure: 'Main: unbounded; company monitoring ceiling £2,323.87/day at 200-stream cap (' + EXPO + ')',
    evidence: 'FC-7 PASS bound to real implementation + staging drill with lowered ceiling.' },
  { id: 'S19', title: 'Rate-of-spend spike', owner: 'WS-FIN', mode: 'automated+manual', status: 'FAIL', controls: ['B5', 'G6'], contract: ['FC-8'],
    precondition: 'Burst of calls across many households.', action: '50 admissions in 60 s.', expected: 'Breaker trips; admissions refused until reset by a human.',
    maxExposure: 'Main: unbounded.', evidence: 'FC-8 PASS bound to real implementation + staging drill.' },
  { id: 'S20', title: 'Compromised credentials create calls', owner: 'OPS / WS-SEC', mode: 'manual', status: 'FAIL', controls: ['A7', 'G5', 'C10'],
    precondition: 'Attacker holds Twilio auth token (or a Voice SDK token, or forges /media-stream).', action: 'Place outbound calls/SMS via REST or forged streams.',
    expected: 'Backend uses a scoped API key; outbound geo off; usage triggers SUSPEND (not just email); rotation runbook executed in drill.',
    maxExposure: 'Unbounded at Twilio account level (master token). Best achievable after subaccount + offline master + Restricted key: prepaid balance + undocumented overrun, pending Twilio written answers (PROVIDER_FINANCIAL_CONTAINMENT_FINAL.md §4, §7).',
    evidence: 'provider-config-export of keys, geo, usage triggers + dated rotation drill + Twilio written answers Q1–Q4.' },
  { id: 'S21', title: 'Customer tampers with client allowance', owner: 'WS-BILL', mode: 'automated', status: 'UNPROVEN', controls: ['B2'], contract: ['FC-4', 'FC-5'],
    precondition: 'Modified app sends forged usage/allowance values.', action: 'Call any usage endpoint with negative/huge values.',
    expected: 'Server is sole authority; client values ignored; negative usage never credits.', maxExposure: 'n/a on main (no allowance).',
    evidence: 'FC-4/FC-5 PASS bound to real implementation + API test that no endpoint accepts client-supplied usage.' },
  { id: 'S22', title: 'RevenueCat sandbox event reaches production path', owner: 'WS-BILL', mode: 'automated+manual', status: 'FAIL', controls: ['D7'], probes: ['PR-08'],
    precondition: 'TestFlight/sandbox purchase.', action: 'RevenueCat posts environment=SANDBOX to production webhook.',
    expected: 'No entitlement and no number in production.', maxExposure: 'Free service + number per sandbox account (unbounded accounts, S1).',
    evidence: 'PR-08 PASS + test asserting no entitlement row for SANDBOX + staging sandbox purchase log.' },
  { id: 'S23', title: 'Stripe duplicate payment event', owner: 'WS-BILL', mode: 'automated', status: 'PARTIAL', controls: ['A3', 'D10'], contract: ['FC-3'],
    precondition: 'Stripe redelivers event.', action: 'Deliver same event.id twice, concurrently.', expected: 'Applied once (claim_stripe_webhook_event).',
    maxExposure: 'Low (dedupe exists).', evidence: 'Automated route test with signed payload delivered twice (absent today).' },
  { id: 'S24', title: 'Apple entitlement delay', owner: 'WS-BILL', mode: 'manual', status: 'UNPROVEN', controls: ['D3'],
    precondition: 'Purchase completes; RevenueCat webhook delayed minutes.', action: 'User proceeds in app.', expected: 'Clear pending state; no free provisioning; eventual consistency.',
    maxExposure: 'Low.', evidence: 'Manual sandbox run with webhook delayed.' },
  { id: 'S25', title: 'Cancelled account still within paid period', owner: 'WS-BILL', mode: 'automated', status: 'PARTIAL', controls: ['D6'],
    precondition: 'cancel_at_period_end.', action: 'Calls during remaining period, then after.', expected: 'Served until period end, cost stops after (B11).',
    maxExposure: 'Main: after expiry calls still connected (B11).', evidence: 'Existing cancellation tests + B11 test.' },
  { id: 'S26', title: 'Subscription expires during active call', owner: 'WS-FIN / WS-BILL', mode: 'automated+manual', status: 'FAIL', controls: ['D11', 'B1'], contract: ['FC-1'], probes: ['PR-06'],
    precondition: 'Expiry timestamp passes mid-call.', action: 'Continue call.', expected: 'Call bounded by the reservation granted at admission and the timeLimit.',
    maxExposure: 'Main: unbounded duration.', evidence: 'Automated + staging.' },
  { id: 'S27', title: 'Two server instances authorise concurrently', owner: 'WS-FIN', mode: 'automated', status: 'FAIL', controls: ['B7'], contract: ['FC-2'],
    precondition: 'Two Node processes share one Postgres.', action: 'Concurrent admissions for the same household.', expected: 'Serialised by the database (advisory lock / FOR UPDATE).',
    maxExposure: 'Main: in-memory counters per instance.', evidence: 'FC-2 PASS with adapter running two processes against pglite-socket/staging Postgres.' },
  { id: 'S28', title: 'Extreme / overflow / malformed cost input', owner: 'WS-FIN', mode: 'automated', status: 'UNPROVEN', controls: ['B9'], contract: ['FC-4'],
    precondition: 'Provider/usage feed returns NaN, negative, 1e308, strings.', action: 'Record usage.', expected: 'Rejected, alert, balance unchanged.',
    maxExposure: 'Corrupt ledger ⇒ breaker blind.', evidence: 'FC-4 PASS bound to real ledger/allowance.' },
  { id: 'S29', title: 'Admin unavailable', owner: 'WS-FIN / OPS', mode: 'manual', status: 'FAIL', controls: ['G6', 'I4'], probes: ['PR-12'],
    precondition: 'Andrew unreachable for 12 h during abnormal spend.', action: 'Spend keeps rising.', expected: 'Automatic suspension without human; documented deputy.',
    maxExposure: 'Main: 12 h × unbounded rate.', evidence: 'Drill showing auto-suspension with no admin action.' },
  { id: 'S30', title: 'App unavailable while carrier forwarding remains active', owner: 'WS-DEL / WS-BILL', mode: 'manual', status: 'PARTIAL', controls: ['F2', 'F3', 'B11', 'H7'],
    precondition: 'App uninstalled / account deleted / subscription ended; customer never removes **21*.', action: 'Callers keep calling.',
    expected: 'No HCG cost beyond inbound leg; number eventually detached; customer warned to remove forwarding; callers hear apology.',
    maxExposure: 'Inbound leg per call (~£0.0076/min) indefinitely while number held (quarantine never auto-releases).',
    evidence: 'Staging uninstall test + lifecycle sweep evidence.' },
];

export const LAUNCH_BLOCKING_SCENARIOS = SCENARIOS.map(s => s.id); // every scenario must be PROVEN before UNRESTRICTED launch
