#!/usr/bin/env node
// HCG launch-gate runner.
//
//   node tests/launch-gate/run.mjs                 # report (exit 0)
//   node tests/launch-gate/run.mjs --enforce       # exit 1 unless every launch-blocking item is PROVEN
//   node tests/launch-gate/run.mjs --json          # machine-readable
//   node tests/launch-gate/run.mjs --markdown      # matrix tables for docs
//   LAUNCH_GATE_FINANCIAL_ADAPTER=path/to/adapter.mjs node tests/launch-gate/run.mjs
//        bind the financial contract (FC-*) to a real implementation;
//        without it every FC-* result is UNPROVEN (never assumed safe).
//
// Read-only and offline: no network, no .env, no database, no provider.

import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { CONTROLS, SCENARIOS, BASELINE } from './registry.mjs';
import { runProbes } from './probes.mjs';
import { runFinancialContract } from './financial-contract.mjs';
import { combine } from './lib/status.mjs';

const args = new Set(process.argv.slice(2));

async function contractResults() {
  const path = process.env.LAUNCH_GATE_FINANCIAL_ADAPTER;
  if (!path) {
    return { bound: null, results: ['FC-1', 'FC-2', 'FC-3', 'FC-4', 'FC-5', 'FC-6', 'FC-7', 'FC-8'].map(id => ({ id, status: 'UNPROVEN', detail: 'no implementation bound (set LAUNCH_GATE_FINANCIAL_ADAPTER)' })) };
  }
  const mod = await import(pathToFileURL(resolve(path)).href);
  return { bound: path, results: await runFinancialContract(mod.createSubject) };
}

export async function evaluate() {
  // Silence module-load chatter from app code the probes require.
  const origErr = console.error, origWarn = console.warn, origLog = console.log;
  console.error = console.warn = console.log = () => {};
  let probes, contract;
  try {
    probes = await runProbes();
    contract = await contractResults();
  } finally {
    console.error = origErr; console.warn = origWarn; console.log = origLog;
  }
  const byId = new Map([...probes, ...contract.results].map(r => [r.id, r]));
  const attach = item => {
    const refs = [...(item.probes || []), ...(item.contract || [])];
    const results = refs.map(id => byId.get(id)).filter(Boolean);
    const { status, stale } = combine(item.status, results);
    return { ...item, claimed: item.status, status, stale, results: results.map(r => ({ id: r.id, status: r.status })) };
  };
  return {
    baseline: BASELINE,
    contractBoundTo: contract.bound,
    probes,
    contract: contract.results,
    controls: CONTROLS.map(attach),
    scenarios: SCENARIOS.map(s => attach({ ...s, blocker: true })),
  };
}

function tally(items) {
  const t = { PROVEN: 0, PARTIAL: 0, UNPROVEN: 0, FAIL: 0 };
  for (const i of items) t[i.status]++;
  return t;
}

function markdown(r) {
  const out = [];
  const esc = s => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
  out.push(`Generated by \`node tests/launch-gate/run.mjs --markdown\` against the working tree (registry baseline ${r.baseline.ref} ${r.baseline.sha}, ${r.baseline.assessed}). Financial contract bound to: ${r.contractBoundTo || 'nothing (FC-* UNPROVEN)'}.\n`);
  out.push('## Executable results\n');
  out.push('| id | kind | result | what it checks | detail |\n|---|---|---|---|---|');
  for (const p of r.probes) out.push(`| ${p.id} | ${p.kind} | **${p.status}** | ${esc(p.title)} | ${esc(p.detail)} |`);
  for (const c of r.contract) out.push(`| ${c.id} | contract | **${c.status}** | scenarios ${c.scenarios ? c.scenarios.join(', ') : ''} | ${esc(c.detail)} |`);
  const areas = { A: 'Security', B: 'Financial', C: 'Telephony fraud', D: 'Billing', E: 'Identity', F: 'Call delivery', G: 'Business continuity', H: 'Customer experience', I: 'Operations' };
  out.push('\n## Control matrix\n');
  for (const [a, name] of Object.entries(areas)) {
    out.push(`### ${a}. ${name}\n`);
    out.push('| id | control | status (main) | launch blocker | owner | evidence | executable | unmerged fix |\n|---|---|---|---|---|---|---|---|');
    for (const c of r.controls.filter(c => c.area === a)) {
      const ev = c.evidence.map(e => `${e.kind}: ${e.ref}`).join('; ');
      const ex = c.results.map(x => `${x.id} ${x.status}`).join(', ');
      out.push(`| ${c.id} | ${esc(c.title)} | **${c.status}**${c.stale ? ' (stale?)' : ''} | ${c.blocker ? 'yes' : 'no'} | ${c.owner} | ${esc(ev)}${c.note ? ` — ${esc(c.note)}` : ''} | ${ex} | ${esc(c.branchFix || '')} |`);
    }
    out.push('');
  }
  out.push('## Adversarial scenarios\n');
  out.push('| id | scenario | status | precondition | action | expected safe result | max financial exposure (main) | mode | evidence required for PROVEN | owner | executable |\n|---|---|---|---|---|---|---|---|---|---|---|');
  for (const s of r.scenarios) {
    out.push(`| ${s.id} | ${esc(s.title)} | **${s.status}** | ${esc(s.precondition)} | ${esc(s.action)} | ${esc(s.expected)} | ${esc(s.maxExposure)} | ${s.mode} | ${esc(s.evidence)} | ${s.owner} | ${s.results.map(x => `${x.id} ${x.status}`).join(', ')} |`);
  }
  out.push(`\nTotals — controls: ${JSON.stringify(tally(r.controls))}; scenarios: ${JSON.stringify(tally(r.scenarios))}`);
  return out.join('\n');
}

const isMain = import.meta.url === pathToFileURL(process.argv[1] || '').href;
if (isMain) {
  const r = await evaluate();
  if (args.has('--json')) console.log(JSON.stringify(r, null, 2));
  else if (args.has('--markdown')) console.log(markdown(r));
  else {
    for (const p of [...r.probes, ...r.contract]) console.log(`${p.status.padEnd(8)} ${p.id}  ${p.detail}`);
    console.log('');
    console.log('controls ', tally(r.controls));
    console.log('scenarios', tally(r.scenarios));
    const blockers = [...r.controls.filter(c => c.blocker), ...r.scenarios].filter(i => i.status !== 'PROVEN');
    console.log(`\nLaunch-blocking items not PROVEN: ${blockers.length}`);
    console.log(blockers.length ? 'GATE: CLOSED — unrestricted launch NOT permitted.' : 'GATE: OPEN');
  }
  if (args.has('--enforce')) {
    const open = [...r.controls.filter(c => c.blocker), ...r.scenarios].some(i => i.status !== 'PROVEN');
    process.exit(open ? 1 : 0);
  }
}
